#端口
server:
  port: 8086
  servlet:
    context-path: /


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tnvote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hcno1999
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**


  #spring.mvc.view.prefix=/WEB-INF/jsp/
  # 响应页面默认后缀
  #spring.mvc.view.suffix=.jsp

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  #cache: false
  #mybatis-plus配置
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  config-location: mybatis-config.xml
  #pagehelper:
  # dialect: mysql
  #reasonable: true
  #support-methods-arguments: true
  #params: count=countSql


#spring-thymeleaf-cache: false
file:
  path: file/**    #文件访问路径
  address:  E://uploadFiles/  #文件保存路径